    <!-- jQuery -->
    <script src="<?php echo $this->baseUrl(); ?>assets/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>assets/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Bootstrap Validator JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>assets/vendor/bootstrap-validator/validator.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>assets/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <!--
    <script src="<?php echo $this->baseUrl(); ?>assets/vendor/raphael/raphael.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>assets/vendor/morrisjs/morris.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>assets/data/morris-data.js"></script>
    -->

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>assets/dist/js/sb-admin-2.js"></script>