<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php if (isset($data['subtitle'])) : ?>
	<title><?php echo $data['subtitle']; ?> | Emergency Resource Management System</title>
	<?php else : ?>
	<title>Emergency Resource Management System</title>
	<?php endif; ?>


    <?php include dirname(__FILE__) . '/css.phtml'; ?>

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading center-block">
						<img class="img-responsive center-block" src="assets/images/logo_v3.png" alt="ERMS Logo">
						<?php if (!empty($data['login_error'])) : ?>
						<div class="alert alert-<?php echo $data['login_error_type']; ?>">
                            <?php echo $data['login_error']; ?>
                        </div>
                        <?php endif; ?>
                        <h3 class="login-heading panel-title text-center">Please Sign in</h3>
                    </div>
                    <div class="panel-body">
                        <form action="<?php echo $this->baseUrl(); ?>login" method="POST" data-toggle="validator">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Username" name="username" type="text" value="<?php echo $data['login_username']; ?>" pattern="[A-Za-z0-9-_.]{6,50}" data-pattern-error="Username does not meet format requirements" required autofocus>
          							<div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="" pattern="[A-Za-z0-9-_.]{8,50}" data-pattern-error="Password does not meet format requirements" required>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                                <?php echo $this->getCsrf(); ?>

                                <!-- Session Hit Counter: <?php echo $data['hits']; ?> -->
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include dirname(__FILE__) . '/js.phtml'; ?>

</body>

</html>
