<div class="container-fluid">
	<div class="row">
        <div class="col-lg-12">
			<h1 class="page-header"><?php echo $data['subtitle']; ?></h1>

            <!--<p>More examples can be found over in the <a target="_blank" href="<?php echo $this->baseUrl(); ?>assets/examples/">Examples</a> folder brought in from the SB Admin 2 template.</p>-->
        </div>
        <!-- /.col-lg-12 -->

    </div>
	<!-- /.row -->

	<div class="row">
		<div class="col-lg-6">
			<form class="form-horizontal" action="<?php echo $this->baseUrl(); ?>add-emergency-incident" method="GET" data-toggle="validator">
                <fieldset>
                    <div class="form-group">
                    	<label for="incident_date" class="col-sm-3 control-label">Date</label>
    					<div class="col-sm-8">
	                        <input required class="form-control" placeholder="Date" id="incident_date" name="incident_date" type="text" value="<?php echo $this->escape($data['parameters']['incident_date']); ?>" pattern="^(?:(?:(?:0?[13578]|1[02])(\/)31)\1|(?:(?:0?[1,3-9]|1[0-2])(\/)(?:29|30)\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:0?2(\/)29\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:(?:0?[1-9])|(?:1[0-2]))(\/)(?:0?[1-9]|1\d|2[0-8])\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$" data-pattern-error="MM/DD/YYYY (e.g. 01/01/2001 or 1/1/2001)" autofocus>
          					<div class="help-block with-errors"></div>
          				</div>
                    </div>

                    <div class="form-group">
                    	<label for="incident_description" class="col-sm-3 control-label">Description</label>
    					<div class="col-sm-8">
	                        <input required class="form-control" placeholder="Description" id="incident_description" name="incident_description" type="text" value="<?php echo $this->escape($data['parameters']['incident_description']); ?>" pattern="[A-Za-z0-9~`!@#\$%\^&\*\(\)_\+-=\{|\}\[\]\|\\:;\',<\.>\?/][A-Za-z0-9~`!@#\$%\^&\*\(\)_\+-=\{|\}\[\]\|\\:;\',<\.>\?/ ]{1,99}" data-pattern-error="Description does not meet format requirements">

	                        <!-- <textarea class="form-control" placeholder="Description" name="incident_description" rows="3" value="<?php //echo $data['parameters']['incident_description']; ?>" pattern="[A-Za-z0-9-_.]{2,50}" data-pattern-error="Search keyword does not meet format requirements"></textarea> -->
          					<div class="help-block with-errors"></div>
          				</div>
                    </div>

                    <div class="form-group">
                      <label for="incident_latitude" class="col-sm-3 control-label">Latitude</label>
                        <div class="col-sm-9">
                          <input required class="form-control" placeholder="Latitude" id="incident_latitude" name="incident_latitude" type="text" value="<?php echo $this->escape($data['parameters']['incident_latitude']); ?>" pattern="^[-+]?([1-8]?\d(\.\d{1,7})?|90(\.0{1,7})?)$" data-pattern-error="Latitude must be between -90.0 and 90.0">
                          <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="form-group">
                      <label for="incident_longitude" class="col-sm-3 control-label">Longitude</label>
                        <div class="col-sm-9">
                          <input required class="form-control" placeholder="Longitude" id="incident_longitude" name="incident_longitude" type="text" value="<?php echo $this->escape($data['parameters']['incident_longitude']); ?>" pattern="^\s*[-+]?(180(\.0{1,7})?|((1[0-7]\d)|([1-9]?\d))(\.\d{1,7})?)$" data-pattern-error="Longitude must be between -180.0 and 180.0">
                          <div class="help-block with-errors"></div>
                        </div>
                    </div>


                    <!-- Change this to a button or input when using this as a form -->
                    <div class="form-group">
                    	<div class="col-sm-offset-3 col-sm-2">
		                    <button type="submit" class="btn btn-lg btn-success" name="submit" value="true">Add</button>
                      </div>
                      <div class=" col-sm-2">
		                    <a href="<?php echo $this->baseUrl(); ?>add-emergency-incident" class="btn btn-lg btn-info">Reset</a>
                    		<?php //echo $this->getCsrf(); ?>
                    	</div>
                    </div>
                </fieldset>
            </form>
	    </div>
	    <!-- /.col-lg-12 -->
      <div class="col-lg-5">
        <?php if ($data['parameters']['save_success'] == true) : ?>
          <div class="alert alert-success">
            Successfully Added New Incident!
          </div>
        <?php endif; ?>
      </div>
	</div>
	<!-- /.row -->
</div>
<!-- /.container-fluid -->