<div class="container-fluid">
<div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Cancel</h1>
        </div>
        <!-- /.col-lg-12 -->
<div class="col-lg-12">
            <p>Canceling Request for  

            <?php if (isset($data['incident_id'])) : ?>    
            <?php echo "Incident ".$data['incident_id']; ?> 
            <?php endif; ?>

            <?php if (isset($data['repair_id'])) : ?>    
            <?php echo "Repair ".$data['repair_id']; ?> 
            <?php endif; ?>

            <?php echo " and Resource Request ".$data['resource_id']; ?>

            </p>
        </div>

        <script type="text/javascript" language="JavaScript">
        function redirect()
            {

                window.location = './resource-status'

            }
        setTimeout(redirect, 2000);     
             </script>


</div>   