<div class="container-fluid">
<div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $data['subtitle']; ?></h1>
        </div>
        <!-- /.col-lg-12 -->

		<div class="row">
			<div class="col-lg-6">
				<form class="form-horizontal" action="<?php echo $this->baseUrl(); ?>deploy-own-resource" method="POST" role="form" data-toggle="validator">
	                <fieldset>
	                    <div class="form-group">
                    		<label for="expected_return_date" class="col-sm-4 control-label">Expected Return Date</label>
    						<div class="col-sm-8">
    							<input type="hidden" name="resource_id" value="<?php echo $data['resourceId']; ?>">
                                <input type="hidden" name="incident_id" value="<?php echo $data['incidentId']; ?>">
                                <input type="hidden" name="redirect" value="<?php echo $data['redirectUrl']; ?>">
		                        <input required class="form-control" placeholder="Expected Return Date" name="expected_return_date" type="text" value="" pattern="^(?:(?:(?:0?[13578]|1[02])(\/)31)\1|(?:(?:0?[1,3-9]|1[0-2])(\/)(?:29|30)\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:0?2(\/)29\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:(?:0?[1-9])|(?:1[0-2]))(\/)(?:0?[1-9]|1\d|2[0-8])\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$" data-pattern-error="MM/DD/YYYY (e.g. 01/01/2001 or 1/1/2001)" autofocus>
          						<div class="help-block with-errors"></div>
          					</div>
	                    </div>

	                    <div class="form-group">
                    	<div class="col-sm-offset-4 col-sm-8">
		                    <button type="submit" class="btn btn-lg btn-success ">Deploy</button>
                    		<?php //echo $this->getCsrf(); ?>
                    	</div>
                    </div>
	                </fieldset>
	            </form>
	        </div>
        </div>


</div>