<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $data['subtitle']; ?></h1>
        </div>
        <!-- /.col-lg-12 -->

    </div>
    <div class="col-lg-12">
        <?php if (empty($data['resourceReport'])) : ?>
            <div class="alert alert-danger"><strong>No resources in use found.</strong></div>
        <?php endif; ?>


        <?php if (!empty($data['resourceReport'])) : ?>
            <div class="panel panel-green">
                <div class="panel-heading">
                    Resource Report
                </div>
                <div class="panel-body">
                	<div class="table-responsive">
	                    <table class="table table-striped table-bordered table-hover">
	                        <thead>
	                        <tr>
	                            <th>ESF ID</th>
	                            <th>Resource Description</th>
	                            <th>Total Resources I Own</th>
	                            <th>Total Resources In Use Which I Own</th>
	                        </tr>
	                        </thead>
	                        <tbody>
	                        <?php foreach($data['resourceReport'] as $row): ?>
	                            <tr>
	                                <td><?= $row->esf_id; ?></td>
	                                <td><?= $row->description; ?></td>
	                                <td><?= $row->total_resources; ?></td>
	                                <td><?= $row->total_resources_in_use; ?></td>
	                            </tr>
	                        <?php endforeach; ?>
	                        <?php foreach($data['resourceReportTotals'] as $row): ?>
	                            <tr>
	                                <td></td>
	                                <td><b>Totals:</b></td>
	                                <td><b><?= $row->sum_total_resources; ?></b></td>
	                                <td><b><?= $row->sum_total_resources_in_use; ?></b></td>

	                            </tr>
	                        <?php endforeach; ?>

	                        </tbody>
	                    </table>
	                </div>
                </div>
            </div>
        <?php endif; ?>





    </div>
</div>