<div class="container-fluid">
<div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $data['subtitle']; ?></h1>
        </div>
        <!-- /.col-lg-12 -->
		<div class="col-lg-12">
			<?php if (!empty($data['resource'])) : ?>
			<div class="panel panel-green">
                    <div class="panel-heading">
                        Details
                    </div>
                    <div class="panel-body">
                    	<table class="table table-bordered">
							<tr>
						  		<th style="width: 20%">Resource ID:</th>
						  		<td style="width: 80%"><?php echo $data['resource']->resource_id; ?></td>
							</tr>
							<tr>
						  		<th>Resource Name:</th>
						  		<td><?php echo $data['resource']->name; ?></td>
							</tr>
							<tr>
						  		<th>Resource Owner:</th>
						  		<td><?php echo $data['resource']->user_name; ?></td>
							</tr>
							<tr>
						  		<th>Resource Model:</th>
						  		<td><?php echo $data['resource']->model; ?></td>
							</tr>
							<tr>
						  		<th>Primary ESF:</th>
						  		<td><?php echo $data['resource']->primary_esf_id . ' - ' . $data['resource']->esf_description; ?></td>
							</tr>
							<tr>
						  		<th>Cost:</th>
						  		<td><?php echo '$' . $data['resource']->cost_amount . '/' . $data['resource']->cost_interval_description; ?></td>
							</tr>
							<tr>
						  		<th>Location (Lat/Long):</th>
						  		<td><a target="_blank" href="http://www.google.com/maps/place/<?= $data['resource']->latitude; ?>,<?= $data['resource']->longitude; ?>"><?php echo $data['resource']->latitude . '/' . $data['resource']->longitude; ?></a></td>
							</tr>
							<?php if (!empty($data['resource']->additionalEsfs)) : ?>
							<tr>
						  		<th>Additional ESFs:</th>
								<td>
									<table class="table table-bordered">
										<tr><th style="width: 20%">ESF ID</th><th style="width: 80%">ESF Description</th></tr>
									<?php foreach($data['resource']->additionalEsfs as $additionalEsf) : ?>
										<tr><th><?= $additionalEsf->esf_id; ?></th><td><?= $additionalEsf->esf_description; ?></td></tr>
									<?php endforeach; ?>
									</table>
								</td>
							</tr>
							<?php endif; ?>
							<?php if (!empty($data['resource']->capabilities)) : ?>
							<tr>
						  		<th>Capabilities:</th>
								<td>
									<table class="table table-bordered">
										<tr><th style="width: 20%">Capability ID</th><th style="width: 80%">Capability Description</th></tr>
									<?php foreach($data['resource']->capabilities as $capability) : ?>
										<tr><th><?= $capability->capability_id; ?></th><td><?= $capability->capability_description; ?></td></tr>
									<?php endforeach; ?>
									</table>
								</td>
							</tr>
							<?php endif; ?>
						</table>


                    </div>
            </div>
            <?php else : ?>
            	<div class="alert alert-danger"><strong>This resource doesn't appear to exist.</strong></div>
            <?php endif; ?>
        </div>

        <!--
		<pre>
		<?php //echo print_r($data['resource'], true); ?>
		</pre>
		-->
</div>