<div class="container-fluid">
	<div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $data['subtitle']; ?></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?php if (empty($data['inUse'])) : ?>
                <div class="alert alert-danger"><strong>No resources in use found.</strong></div>
            <?php endif; ?>


            <?php if (!empty($data['inUse'])) : ?>
                <div class="panel panel-green" id="resources-in-use">
                    <div class="panel-heading">
                        Resources In Use (<?= count($data['inUse']); ?>)
                    </div>
                    <div class="panel-body">
                    	<div class="table-responsive">
	                        <table class="table table-striped table-bordered table-hover">
	                            <thead>
	                                <tr>
	                                    <th>Resource ID</th>
	                                    <th>Resource Name</th>
	                                    <th>Incident ID</th>
	                                    <th>Incident Responding To</th>
	                                    <th>Owner</th>
	                                    <!--<th>Start Date</th>
	                                    <th>Return By</th>-->
	                                    <th>Action</th>
	                                </tr>
	                            </thead>
	                            <tbody>
	                                <?php foreach($data['inUse'] as $row): ?>
	                                <tr>
	                                    <td><?= $row->resource_id; ?></td>
	                                    <td><?= $row->name; ?></td>
	                                    <td><?= $row->incident_id; ?></td>
	                                    <td><?= $row->description; ?></td>
	                                    <td><?= $row->resource_owner_name; ?></td>
	                                    <!--<td><?= $row->expected_return_date; ?></td>
	                                    <td><?= $row->start_date; ?></td>-->
	                                    <td><form action="return-resource">
	                                    <input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
	                                    <input type="hidden" name="incident_id" value="<?php echo $row->incident_id; ?>">
	                                    <button type="submit" class="btn btn-primary ">Return</button></form></td>
	                                </tr>
	                                <?php endforeach; ?>
	                            </tbody>
	                        </table>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

             <?php if (empty($data['requestedByMe'])) : ?>
                <div class="alert alert-danger"><strong>You have no outgoing resource requests.</strong></div>
            <?php endif; ?>

            <?php if (!empty($data['requestedByMe'])) : ?>
                <div class="panel panel-green" id="my-pending-requests">
                    <div class="panel-heading">
                       Resources Requested By <?php echo $data['user']->name; ?> (<?= count($data['requestedByMe']); ?>)
                    </div>
	                <div class="panel-body">
	                    <div class="table-responsive">
		                    <table class="table table-striped table-bordered table-hover">
		                        <thead>
		                            <tr>
		                                <th>Resource ID</th>
		                                <th>Resource Name</th>
		                                <th>Incident ID</th>
		                                <th>Incident Name</th>
		                                <th>Owner</th>
		                                <!--<th>Return By</th>-->
		                                <th>Action</th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <?php foreach($data['requestedByMe'] as $row): ?>
		                            <?php if ($row->resource_owner_name==$data['user']->name) : continue; ?>
		                            <?php endif; ?>
		                            <tr>
		                                <td><?= $row->resource_id; ?></td>
		                                <td><?= $row->name; ?></td>
		                                <td><?= $row->incident_id; ?></td>
		                                <td><?= $row->description; ?></td>
		                                <td><?= $row->resource_owner_name; ?></td>
		                                <!--<td><?= $row->expected_return_date; ?></td>-->
		                                <td><form action="cancel">
		                                <input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
		                                <input type="hidden" name="incident_id" value="<?php echo $row->incident_id; ?>">
		                                <button type="submit" class="btn btn-primary ">Cancel</button></form></td>

		                                </tr>
		                            <?php endforeach; ?>
		                        </tbody>
		                    </table>
		                </div>
                	</div>
            	</div>
            <?php endif; ?>

            <?php if (empty($data['receivedByMe'])) : ?>
                <div class="alert alert-danger"><strong>None of the resources you own have any resource requests.</strong></div>
            <?php endif; ?>

            <?php if (!empty($data['receivedByMe'])) : ?>
	            <div class="panel panel-green" id="requests-pending-approval">
	                <div class="panel-heading">
	                    Resource Requests Received By <?php echo $data['user']->name; ?> (<?= count($data['receivedByMe']); ?>)
	                </div>
	                <div class="panel-body">
	                    <div class="table-responsive">
		                    <table class="table table-striped table-bordered table-hover">
		                        <thead>
		                            <tr>
		                                <th>Resource ID</th>
		                                <th>Resource Name</th>
		                                <th>Incident ID</th>
		                                <th>Incident Name</th>
		                                <th>Requested By</th>
		                                <!--<th>Return By</th>-->
		                                <th>Action</th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <?php foreach($data['receivedByMe'] as $row): ?>
		                            <?php if ($row->requester_name==$data['user']->name) : continue; ?>
		                            <?php endif; ?>
		                            <!--it is possible we'll just want to filter this in ResourceStatus model but leaving as done for now-->
		                            <tr>
		                                <td><?= $row->resource_id; ?></td>
		                                <td><?= $row->name; ?></td>
		                                <td><?= $row->incident_id; ?></td>
		                                <td><?= $row->description; ?></td>
		                               <td><?= $row->requester_name; ?></td>
		                               <!--<td><?= $row->expected_return_date; ?></td>-->
		                                <td>
			                                <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
				                                <form action="deploy-resource">
					                                <input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
					                                <input type="hidden" name="incident_id" value="<?php echo $row->incident_id; ?>">
					                                <button type="submit" class="btn btn-primary ">Deploy</button>
					                            </form>
				                                <form action="reject-request">
					                                <input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
					                                <input type="hidden" name="incident_id" value="<?php echo $row->incident_id; ?>">
					                                <button type="submit" class="btn btn-primary ">Reject</button>
					                            </form>
				                            </div>
			                            </td>
		                                </tr>
		                            <!--TODO: Need to change button display based on status-->

		                            <?php endforeach; ?>
		                        </tbody>
		                    </table>
		                </div>
	                </div>
	            </div>
            <?php endif; ?>

            <?php if (empty($data['repairsScheduled'])) : ?>
                <div class="alert alert-danger"><strong>No repairs are scheduled for your resources.</strong></div>
            <?php endif; ?>

            <?php if (!empty($data['repairsScheduled'])) : ?>
	            <div class="panel panel-green" id="scheduled-repairs">
	                <div class="panel-heading">
                    	Repairs Scheduled or In Progress (<?= count($data['repairsScheduled']); ?>)
	                </div>
	                <div class="panel-body">
                    	<div class="table-responsive">
		                    <table class="table table-striped table-bordered table-hover">
		                        <thead>
		                            <tr>
		                                <th>Resource ID</th>
		                                <th>Resource Name</th>
		                                <th>Start On</th>
		                                <th>Ready By</th>
		                                <th>Action</th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <?php foreach($data['repairsScheduled'] as $row): ?>
		                            <tr>
		                                <td><?= $row->resource_id; ?></td>
		                                <td><?= $row->name; ?></td>
		                                <td><?= $row->start_date; ?></td>
		                                <td><?= $row->end_date; ?></td>
		                                <td> <?php if ($row->repair_status_id==2) :
		                                        echo "</td></tr>";continue; ?>
		                                     <?php endif; ?>
		                                <form action="cancel">
		                                <input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
		                                <input type="hidden" name="repair_id" value="<?php echo $row->repair_id; ?>">
		                                <button type="submit" class="btn btn-primary ">Cancel</button></form></td>
		                                </tr>
		                            <?php endforeach; ?>
		                        </tbody>
		                    </table>
		                </div>
	                </div>
	            </div>
            <?php endif; ?>

    	</div>
	</div>
</div>
<!-- /.container-fluid -->