<div class="container-fluid">
	<div class="row">
        <div class="col-lg-12">
			<h1 class="page-header"><?php echo $data['subtitle']; ?></h1>

			<?php if (!empty($data['message'])) : ?>
				<div class="alert alert-<?php echo $data['message_type']; ?>">
			        <?php echo $data['message']; ?>
			    </div>
			<?php endif; ?>
            <!--<p>More examples can be found over in the <a target="_blank" href="<?php echo $this->baseUrl(); ?>assets/examples/">Examples</a> folder brought in from the SB Admin 2 template.</p>-->
        </div>
        <!-- /.col-lg-12 -->

    </div>
	<!-- /.row -->

	<div class="row">
		<div class="col-lg-4">
			<form class="form-horizontal" action="<?php echo $this->baseUrl(); ?>search-resources" method="GET" data-toggle="validator">
                <fieldset>
                    <div class="form-group">
                    	<label for="search_keyword" class="col-sm-3 control-label">Keywords</label>
    					<div class="col-sm-9">
	                        <input class="form-control" placeholder="Keywords" id="search_keyword" name="search_keyword" type="text" value="<?php echo $this->escape($data['parameters']['search_keyword']); ?>" pattern="[A-Za-z0-9-\[\] _.]{2,50}" data-pattern-error="Search keyword does not meet format requirements" autofocus>
          					<div class="help-block with-errors"></div>
          				</div>
                    </div>

                    <div class="form-group">
                    	<label for="search_esf" class="col-sm-3 control-label">ESF</label>
    					<div class="col-sm-9">
	                        <?php echo $data['model']->getEsfsDropdown($data['parameters']['search_esf']); ?>
          					<div class="help-block with-errors"></div>
          				</div>
                    </div>

					<div class="form-group">
                    	<label for="search_incident" class="col-sm-3 control-label">Incident</label>
    					<div class="col-sm-9">
	                        <?php echo $data['model']->getIncidentsDropdown($data['parameters']['search_incident']); ?>
          					<div class="help-block with-errors"></div>
          				</div>
                    </div>

                    <div class="form-group" id="search_radius_container">
                    	<label for="search_radius" class="col-sm-3 control-label">Location</label>
    					<div class="col-sm-9">
							<span>Within</span>
							<input class="form-control small-inline" placeholder="" id="search_radius" name="search_radius" type="text" value="<?php echo (!empty($data['parameters']['search_radius'])) ? (int) $data['parameters']['search_radius'] : ''; ?>" pattern="[0-9]{1,4}" data-pattern-error="Search radius does not meet format requirements">
							<span>Kilometers of incident</span>
          					<div class="help-block with-errors"></div>
          				</div>
                    </div>

                    <!-- Change this to a button or input when using this as a form -->
                    <div class="form-group">
                    	<div class="col-sm-offset-3 col-sm-9">
		                    <button type="submit" class="btn btn-lg btn-success ">Search</button>
		                    <a href="<?php echo $this->baseUrl(); ?>search-resources" class="btn btn-lg btn-info">Reset</a>
                    		<?php //echo $this->getCsrf(); ?>
                    	</div>
                    </div>
                </fieldset>
            </form>
	    </div>
	    <div class="col-lg-8">
	    	<?php if (empty($data['results']) && $data['parameters']['search'] === true) : ?>
				<div class="alert alert-danger"><strong>No results were returned, please try adjusting your search.</strong></div>
	    	<?php endif; ?>
	    	<?php if (!empty($data['results'])) : ?>
	    		<div class="panel panel-green">
                	<div class="panel-heading">
						<?php echo count($data['results']); ?> Search Results:
					</div>
					<div class="panel-body">
						<?php if (!empty($data['incident'])) : ?>
						<div class="alert alert-info">Currently selected Incident <strong><a target="_blank" href="http://www.google.com/maps/place/<?= $data['incident']->latitude; ?>,<?= $data['incident']->longitude; ?>">#<?= $data['incident']->incident_id; ?> - <?= $data['incident']->description; ?></a></strong></div>
						<?php endif; ?>
						<div class="table-responsive">
							<table class="table table-striped table-bordered table-hover vertical-align">
				                <thead>
				                    <tr>
				                        <th>Resource ID</th>
				                        <th>Resource Name</th>
				                        <th>Owner</th>
				                        <th>Cost</th>
				                        <th>Status</th>
				                        <th>Next Available</th>
				                        <?php if (!empty($data['incident'])) : ?>
				                        <th>Distance</th>
				                        <th>Actions</th>
				                        <?php endif; ?>
				                    </tr>
				                </thead>
				                <tbody>
                					<?php foreach($data['results'] as $row): ?>
				                    <tr>
				                        <td><a href="<?= $this->baseUrl().'resources/'.$row->resource_id;?>"><?= $this->escape($row->resource_id); ?></a></td>
				                        <td><?= $this->escape($row->name); ?></td>
				                        <td><?= $this->escape($row->owner); ?></td>
				                        <td><?= '$' . $this->escape($row->cost_amount) . '/' . $this->escape($row->cost_interval_description); ?></td>
				                        <td><?= $this->escape($row->resource_status); ?></td>
				                        <?php if ($row->resource_status === 'available') : ?>
				                        <td>NOW</td>
				                        <?php elseif ($row->resource_status === 'in-use')  : ?>
										<td><?php echo (isset($data['inUseReturnDates'][$row->resource_id])) ? $this->carbon($data['inUseReturnDates'][$row->resource_id]->expected_return_date)->toFormattedDateString() : ''; ?></td>
				                        <?php elseif ($row->resource_status === 'in-repair')  : ?>
										<td><?php echo (isset($data['inRepairReturnDates'][$row->resource_id])) ? $this->carbon($data['inRepairReturnDates'][$row->resource_id]->end_date)->toFormattedDateString() : ''; ?></td>
				                        <?php else : ?>
										<td>LATER?</td>
				                        <?php endif; ?>
				                        <?php if (!empty($data['incident'])) : ?>
				                        <td><a target="_blank" href="https://www.google.com/maps/dir/'<?= $data['incident']->latitude; ?>,<?= $data['incident']->longitude; ?>'/'<?= $row->latitude; ?>,<?= $row->longitude; ?>'"><?= $row->distance_from_incident_in_km; ?> km</a></td>
				                        <td>
			                        		<?php if (!isset($data['previouslyDeployedResources'][$row->resource_id])) : ?>
			                        			<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">

			                        			<?php if (!isset($data['inUseResourcesList'][$row->resource_id])) : ?>

													<?php if (isset($data['requestedResourcesList'][$row->resource_id])) : ?>
															<form action="<?= $this->baseUrl(); ?>cancel" method="GET">
                                    							<input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
                                    							<input type="hidden" name="incident_id" value="<?php echo $data['incident']->incident_id; ?>">
                                    							<input type="hidden" name="redirect" value="<?php echo base64_encode($_SERVER['REQUEST_URI']); ?>">
                                    							<button type="submit" class="btn btn-sm btn-danger">Cancel Request</button>
                                    						</form>
													<?php endif; ?>
													<?php if ($row->user_id === $data['user']->user_id && $row->resource_status === 'available') : ?>
														<form action="<?= $this->baseUrl(); ?>deploy-own-resource" method="GET">
                                    						<input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
                                    						<input type="hidden" name="incident_id" value="<?php echo $data['incident']->incident_id; ?>">
                                    						<input type="hidden" name="redirect" value="<?php echo base64_encode($_SERVER['REQUEST_URI']); ?>">
                                    						<button type="submit" class="btn btn-sm btn-success">Deploy</button>
                                    					</form>
													<?php elseif ($row->user_id !== $data['user']->user_id && ($row->resource_status === 'available' || $row->resource_status === 'in-use')) : ?>
														<?php if (!isset($data['requestedResourcesList'][$row->resource_id])) : ?>
															<form action="<?= $this->baseUrl(); ?>request-resource" method="GET">
                                    							<input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
                                    							<input type="hidden" name="incident_id" value="<?php echo $data['incident']->incident_id; ?>">
                                    							<input type="hidden" name="redirect" value="<?php echo base64_encode($_SERVER['REQUEST_URI']); ?>">
                                    							<button type="submit" class="btn btn-sm btn-info">Request</button>
                                    						</form>
														<?php endif; ?>

													<?php endif; ?>


												<?php endif; ?>

												<?php if ($row->user_id === $data['user']->user_id && $row->resource_status !== 'in-repair') : ?>
													<form action="<?= $this->baseUrl(); ?>repair-resource" method="GET">
                                    					<input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
                                    					<input type="hidden" name="resource_status" value="<?php echo $row->resource_status; ?>">
                                    					<input type="hidden" name="redirect" value="<?php echo base64_encode($_SERVER['REQUEST_URI']); ?>">
                                    					<button type="submit" class="btn btn-sm btn-warning">Repair</button>
                                    				</form>
												<?php endif; ?>
												</div>
											<?php else : ?>
												<?php if ($row->user_id === $data['user']->user_id && $row->resource_status !== 'in-repair') : ?>
													<form action="<?= $this->baseUrl(); ?>repair-resource" method="GET">
                                    					<input type="hidden" name="resource_id" value="<?php echo $row->resource_id; ?>">
                                    					<input type="hidden" name="resource_status" value="<?php echo $row->resource_status; ?>">
                                    					<input type="hidden" name="redirect" value="<?php echo base64_encode($_SERVER['REQUEST_URI']); ?>">
                                    					<button type="submit" class="btn btn-sm btn-warning">Repair</button>
                                    				</form>
                                    			<?php else : ?>
                                    				<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                                    					<button class="btn btn-sm btn-danger" disabled>Previously Deployed</button>
                                    				</div>
												<?php endif; ?>
											<?php endif; ?>
				                        </td>
				                        <?php endif; ?>
				                    </tr>
				                    <?php endforeach; ?>
				                </tbody>
				            </table>
				        </div>
						<!--
						<pre><?php //echo print_r($data['results'], true); ?></pre>
						<pre><?php //echo print_r($data['resourcesRequestedByMe'], true); ?></pre>
						-->

					</div>
				</div>
			<?php endif; ?>
		</div>
	    <!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
</div>
<!-- /.container-fluid -->